### ISSUE TITLE
Cart Create Fail

### ISSUE THREAD

**Issue by libterty** [libterty/ecommerce_frontend#21]
```bash
mapCartInventory() {
    return this.initCart.map(item => ({
      ProductId: item.ProductId,
      ColorId: item.ColorId,
      quantity: item.quantity
    }))
},
checkCartInventory() {
    return {
      notEnough:
        this.productInCart.quantity + this.form.quantity >
        this.selectedColorQuantity ||
        this.productInCart.quantity > this.selectedColorQuantity
    }
 }
```

這兩個Compute會造成使用者在按下選擇新增顏色時就噴錯，AddToCart也會因為之前的Undefined錯誤掛掉
![Screen Shot 2020-01-29 at 2 38 48 PM](https://user-images.githubusercontent.com/38395851/73333561-1d7d2800-42a5-11ea-9378-98aeccd0de8d.png)

**Comment by mpragnarok** [comment]
Fixed in [commit 4c9b48c](https://github.com/libterty/ecommerce_frontend/commit/4c9b48cd229c9c7e9c9b9d469a054a6042ad862b) and close the issue
